config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  root "messages#index"
  resources :messages, only: :index do
    collection do
      # 検索結果の表示に詳細ページなどは必要ない
      get 'search'
    end
  end
  resources :posts, only: [:index, :new, :create, :get] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
    end
  end
  resources :users, only: :index
  resources :regions, only: :index

  get 'maps/index'
  # root to: 'maps#index'
  resources :maps, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post
  has_ancestry
  # has_many :post_category_relations
  # has_many :posts, through: :post_category_relations
end

app/models/check.rb
class Check < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  # def self.
  def self.search(search)
    # サーチメソッドを作っている
    if search
      Post.where(['(content LIKE ?)  OR  (areaname LIKE ?) OR (medium_area LIKE ?)', "%#{search}%", "%#{search}%", "%#{search}%"])
      # Post.where(['content LIKE ?', "%#{search}%"])
      # Postモデルのcontentカラムで検索
    else
      Post.all
    end
  end

  def self.fsearch
    # サーチメソッドを作っている
    
      # Post.where(['content LIKE ?', or 'areaname LIKE ?', "%#{search}%","%#{search}%"])
    Post.where(check_1: "初心者にオススメ")
      # Postモデルのcontentカラムで検索
  
    
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  
  validates :content,presence: true
  mount_uploader :image, ImageUploader

  default_scope -> { order(id: :desc) }

  # has_many :post_category_relations
  # has_many :categories, through: :post_category_relations
  

  # accepts_nested_attributes_for :post_category_relations
  # has_many :post_prefecture_relations
  # has_many :prefectures, through: :post_prefecture_relations
  # validates :check_1, presence: true, uniqueness: true
end

app/models/post_prefecture_relation.rb
class PostPrefectureRelation < ApplicationRecord
  belongs_to :post
  belongs_to :prefecture

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :post_prefecture_relations
  has_many :posts, through: :post_prefecture_relations
end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_post

  def index
    
    @posts = Post.all
    # postsコントローラーの変数、これが無いとpostで送った内容が表示できない
    @messages = 'message'
    @fmessages = 'feature_message'
    # massageビューでこの変数を使う、messageURLが入っている
    @headers = 'header'
    @posts = Message.search(params[:search])
    @fposts = Message.fsearch
    # @postsf = Post.all(params[:areanames])

  end

  # def search
  #   #Viewのformで取得したパラメータをモデルに渡す
  #   #インスタンス変数@postsは ビューから送られたパラメーター検索語を受け取り
  #   @posts = Message.search(params[:search]),(search_params)
  #   # messgaeモデルのサーチメソッドの呼び出し[ビューのフォームでの引数をいれる]
  # end  

  # private
  # def set_post
  #   @group = Group.find(params[:group_id])
  # end
  # messagesコントローラーの全てのアクションで@groupを利用できるようにしている

  private
  def search_params
    params.permit(:content, :search, :areaname)
  end
end
# class MessagesController < ApplicationController
#   def index
#     @posts = Post.all
#   end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  before_action :set_category_links, only: :category_item_lists
  # before_action :post_params, only: [:index, :new, :create]

  def index
    @posts = Post.all
    @category_parent_array = Category.where(ancestry: nil)
    @post = Post.new
  


    # @prefectures = Prefecture.all
    @headers = 'messages/header'
  end

  def new
    @post = Post.new
   

  end


  def create
    
    Post.create(post_params)
    
    
    # Category.create(category_params)
    # Post_category_relation.create(post_category_params)
    # category様にpermit指定したこのテーブルのカラムだけでよし多対多の関連付けのおかげかも
  end

  def get_category_children
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_children_edit
    @category_children_edit = Category.find(params[:category_id]).children
  end

  # def search
  #   #Viewのformで取得したパラメータをモデルに渡す
  #   #インスタンス変数@postsは ビューから送られたパラメーター検索語を受け取り
  #   @posts = Message.search(params[:search])
  #   # messgaeモデルのサーチメソッドの呼び出し[ビューのフォームでの引数をいれる]
  # end  
 

  private
  # def post_params
  #   params.permit(:areaname, :content, :genre, :large_area, :medium_area, :check_1, :check_2, :check_3, :check_4, :check_5, :check_6, :check_7, :check_8, :check_9, :image, :level, :category_id, :name, :ancestry)
  # end

  def post_params
    params.require(:post).permit(:areaname, :content, :genre, :large_area, :medium_area, :check_1, :check_2, :check_3, :check_4, :check_5, :check_6, :check_7, :check_8, :check_9, :image, :level, :category_id, :name, :ancestry)
  end


  # def category_params
  #   params.permit(:check_1, :check_id, :post_id, :category_id)
  # end





  # def set_category
  #   @category_parent_array = Category.where(ancestry: nil)
  # end
  # def post_category_params
  #   params.permit(:category_id, :post_id)
  # end

end



# class PostsController < ApplicationController
  
#   def index
#     @posts = Post.all
#   end

#   def new
#     @post = Post.new
#   end


#   def create
#     def create
#       Post.create(post_params)

#     end
    
#   end

 
#   private
#   def post_params
#     params.permit(:areaname, :content, :large_area, :check_1, :image)

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  # def index
  #   @regions = Region.all(region_params)
  # end


  # private
  # def region_params
  #   params.permit :name
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/items/index.html.haml
%h1 Items#index
%p Find me in app/views/items/index.html.haml

app/views/messages/_feature_message.html.haml
- @fposts.each do |post|
  .Message__box-f
    -# = link_to message_path, index, areanames: @post.areaname
    .Message__boxleft-f
      -# = link_to '初心者オススメ', 'message_path', action: 'index', check_1: '初心者にオススメ'
      .Message__image-f
        = image_tag post.image.url, size: "100x100"
      .Message__contents-f
        .Message__contentsname-f
          = post.areaname
        .Message__contentsarea-f
          = post.medium_area

app/views/messages/_header.html.haml
.Headermenu
  %ul.Headermenu__left
    %li.Headermenu__top
      = link_to '←旅ログ', '/messages'
  %ul.Headermenu__right
    %li.Headermenu__new
      新規登録
    %li.Headermenu__itembar
      |
    %li.Headermenu__login
      ログイン
    %li.Headermenu__itembar
      |
    %li.Headermenu__mypage
      マイページ

      -# %p jQuery稼働テスト
      -# :javascript
      -#   $(document).ready(function() {
      -#     $("p").text("jQuery稼働テスト(稼働中)");
      -#   });

app/views/messages/_main_message.html.haml
.Main
  .Message
    -# = render partial: 'message', locals: {message: post.content}
    .Message__group
      .Messagegroup__left
        = render @messages
      .Messagegroup__right
        .Messagegroup__righttext
          %span ●特集
          [初心者にオススメ]
        = render @fmessages
    -# .Message__box
    -#   .Message__boxleft
    -#     .Message__image
    -#       -# = image_tag @post.image_url, class: 'Message__imagea' if @post.image.present?
    -#     .Message__userbox
    -#       .Message__user
    -#         投稿者：
    -#       .Message__username
    -#         uni
    -#       .Message__nice
    -#         イイね❤︎2
    -#   .Message__boxright
    -#     .Message__contents
    -#       .Message__contentsname
    -#         - @posts.each do |post|
    -#           = post.content
    -#         -# - @posts.each do |post|
    -#         -#   = post.content
    -#       .Message__contentsarea
    -#         [松原市]
    -#       .Message__contentscoment
    -#         %p 良い！すごく良い
    -#         %p 素晴らしい
    -#         %p イイかもね
    -#       .Message__contentsspoint
    -#         %p 安い



  -#           .Main
  -# .Message
  -#   .Message__box
  -#     .Message__boxleft
  -#       .Message__image
  -#         = image_tag post.image.url, if post.image.present?
  -#            -# = image_tag post.image.url, class: 'Message__images' if post.image.present?
  -#       .Message__userbox
  -#         .Message__user
  -#           投稿者：
  -#         .Message__username
  -#           uni
  -#         .Message__nice
  -#           イイね❤︎2
  -#     .Message__boxright
  -#       .Message__contents
  -#         .Message__contentsname
  -#           白谷雲水峡
  -#         .Message__contentsarea
  -#           [松原市]
  -#         .Message__contentscoment
  -#           %p 良い！すごく良い
  -#           %p 素晴らしい
  -#           %p イイかもね
  -#         .Message__contentsspoint
  -#           %p 安い

app/views/messages/_message.html.haml
-# - @posts.each do |post|
- @posts.each do |post|
  .Message__box
    .Message__boxleft
      .Message__image
        = image_tag post.image.url
      .Message__userbox
        .Message__user
          投稿者：
        .Message__username
          test
        .Message__nice
          イイね❤︎2
    .Message__boxright
      .Message__contents
        .Message__contentsname
          スポット名: 
          = post.areaname
        .Message__contentsgenre
          ジャンル: 
          = post.genre
        .Message__contentsarea
          エリア:
          = post.medium_area
        .Message__contentslevel
          ソロ活難易度:
          = post.level
        .Message__contentscoment
          コメント: 
          = safe_join(post.content.split("\n"), tag(:br))
          -# = post.content
        .Message__contentsspoint
          %ul 
            [こだわりポイント]
            %li
              = post.check_1
            %li
              = post.check_2
            %li
              = post.check_3
            %li
              = post.check_4
            %li
              = post.check_5
            %li
              = post.check_6
            %li
              = post.check_7
            %li
              = post.check_8
            %li
              = post.check_9
  -# .Sarch
  -#   %ul 
  -#     - @messages.each do |post|
  -#       %li
  -#         = link_to post.areaname, post
          
  -#         = post.created_at
  -#         = post.status
      -# %li
      -# = link_to "編集",edit_post_path(post)
      -# = link_to "削除",post, method: :delete


-# - @posts.each do |post|
-#   .Message__box
-#     .Message__boxleft
-#       .Message__image
-#         = image_tag post.image.url
-#       .Message__userbox
-#         .Message__user
-#           投稿者：
-#         .Message__username
-#           uni
-#         .Message__nice
-#           イイね❤︎2
-#     .Message__boxright
-#       .Message__contents
-#         .Message__contentsname
-#           スポット名: 
-#           = post.areaname
-#         .Message__contentsarea
-#           エリア: 
-#           = post.medium_area

-#         .Message__contentscoment
-#           コメント: 
-#           = safe_join(post.content.split("\n"), tag(:br))
-#           -# = post.content
-#         .Message__contentsspoint
-#           %ul 
-#             [こだわりポイント]
-#             %li
-#               = post.check_1
-#             %li
-#               = post.check_2
-#             %li
-#               = post.check_3
-#             %li
-#               = post.check_4
-#             %li
-#               = post.check_5
-#             %li
-#               = post.check_6
-#             %li
-#               = post.check_7
-#             %li
-#               = post.check_8
-#             %li
-#               = post.check_9

app/views/messages/_side_bar.html.haml
.Sidebar
  .Sidebarmain
    .Map
    %h2 GoogleMap検索
    %input#address{:type => "textbox", :value => ""}/
    %input{:onclick => "codeAddress()", :type => "button", :value => "Search"}/

    #map
    :css
      #map {
        height: 250px;
        width: 250px;
      }
    :javascript
      let map

      function initMap(){
        geocoder = new google.maps.Geocoder()

        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 34.6873, lng:135.5259},
          zoom: 8,
        });

        marker = new google.maps.Marker({
          position:  {lat: 43.7828, lng:-73.9653},
          map: map
        });
      }
      let geocoder

      function codeAddress(){
        let inputAddress = document.getElementById('address').value;

        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
          if (status == 'OK') {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
          } else {
            alert('該当する結果がありませんでした：' + status);
          }
        });   
      }


    %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyDFVB5jgBHoEaTVm7DaX-64NE8-wvXtGWU&callback=initMap"}

    .Sidebarmain__areabox
      %h1 エリアから選ぶ
    .Sidebarmain__drop
      .Mainpost__genre
        関西
        -# = f.select, [["アウトドア", "アウトドア"], ["屋内", "屋内"], ["飲食", "飲食"], ["お酒", "お酒"]], {include_blank: "ジャンルを選んで下さい"}, {class: ''}
    .Sidebarmain__list
      %ul
        %li
          = link_to '大阪', 'post', action: 'index', check_1: '初心者にオススメ'
        %li
          = link_to '京都', 'post', action: 'index', check_1: '初心者にオススメ'
        %li
          = link_to '奈良', 'post', action: 'index', check_1: '初心者にオススメ'
      %ul
        %li
          = link_to '三重', 'post', action: 'index', check_1: '初心者にオススメ'
        %li
          = link_to '兵庫', 'post', action: 'index', check_1: '初心者にオスス'
        %li  
          = link_to '滋賀', 'post', action: 'index', check_1: '初心者にオススメ'
      %ul
        %li
          = link_to '和歌山', 'post', action: 'index', check_1: '初心者にオススメ'

    .Sidebarmain__ldentify
      %h1 こだわりポイントで探す
      .Sidebarmain__ldentifylist
        %ul
          %li
            = link_to '初心者にオススメ', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to '中級者以上にオススメ', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to '上級者向け', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to '携帯電波有り', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to 'お一人様多数', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to '人通り[少]', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to 'カウンター席有り', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to '近くに薬局', 'post', action: 'index', check_1: '初心者にオススメ'
          %li
            = link_to 'アウェー感[少]', 'post', action: 'index', check_1: '初心者にオススメ'

app/views/messages/_top_header.html.haml
.Header
  = render @headers
  .Headermain
    -# .Headermain__images
    .Headermain__pagename
      -# = image_tag '/assets/logo1.PNG', height: '200em', width: '200em', class: 'hoge'
      = image_tag asset_path('logo1.PNG'), height: '200em', width: '200em', class: 'hoge'

    .Headermain__right
      .Headermain__righttext
        %p ひとり旅が好き？
        %span 私はひとり旅も好き
      .Headermain__rightimages
        .Headermain__rightimage
          = image_tag asset_path('logo2.jpg'), height: '100em', width: '100em', class: 'hoge'
          -# = image_tag '/assets/logo2.jpg', height: '100em', width: '100em', class: 'hoge'
  .Headerlist
    .Headerlist__group 
      .Headerlist__searchbox
        .Headerlist__text
          キーワード検索：
        .Headerlist__search
          = form_tag messages_path, :method => 'get' do
            = text_field_tag :search
            -# 検索を押したリンク先（2つ上）
            -# コントローラーで定義するパラメーター名に値を送る、モデルにいく
            = submit_tag '検索', :name => nil
            -# URLの後ろに余計な検索がつく、いらないのでnil
      .Headerlist__right
        .Headerlist__post
          = link_to "投稿する", posts_path, class: 'Button'

app/views/messages/index.html.haml
.wrapper
  = render "top_header"
  .maincontent
    = render "side_bar"
    = render "main_message"

app/views/posts/_postpage.html.haml
= render @headers
.Posts
  -# = render @headers
  -# = form_with model:@post, html: {class: 'Mainpost'}, local: true do |f|
  = form_with model:@post, class: 'Mainpost', local: true do |f|

    .Mainpost__postform
      .Mainpost__box
        .Mainpost__boxleft
          = f.label :image, class: 'image_label' do
            -# .prev-contents
            -#   -# 既に登録されている画像があれば表示をさせます
            -#   - if image.present?
            -#     .prev-content
            -#       = image_tag image.url, alt: "preview", class: "prev-image"
            -#   -# 既に登録されている画像がなければiconを表示させます
            -#   - else
            -#     = icon('fas', 'image', class: 'photo-icon')
            -# -# file_fieldはdisplay: none;で隠します
            = f.file_field :image, class: 'Mainpost＿＿image'





          -# = f.file_field :image, class: 'Mainpost__image'
        .Mainpost__boxright
          .Mainpost__inputname
            = f.text_field :areaname, placeholder: 'スポット名を入力して下さい', class: 'formbox'
          .Mainpost__genre
            = f.select :genre, [["アウトドア", "アウトドア"], ["屋内", "屋内"], ["アミューズメント", "アミューズメント"],["遺跡", "遺跡"],["城", "城"], ["飲食", "飲食"], ["お酒", "お酒"]], {include_blank: "ジャンルを選んで下さい"}, {class: 'formbox'}
          .Mainpost__inputarea
            -# = f.select :large_area, [["北海道", "北海道"], ["東北", "東北"], ["アミューズメント", "アミューズメント"],["遺跡", "遺跡"],["城", "城"], ["飲食", "飲食"], ["お酒", "お酒"]], {include_blank: "地方を選んで下さい"}, {class: 'formbox'}
            = f.collection_select :category_id, @category_parent_array, :id, :name, {include_blank: "地方を選んで下さい"}, class: "listing-select-wrapper__box--select", id: "parent_category"
            .listing-product-detail__category
            -# = f.collection_select :large_area, @category_parent_array, :name, :name, {include_blank: "地を選んで下さい"}, class: "formbox"
          -# .Mainpost__inputmediumarea
          -#   = f.select :medium_area, [["北海", "北海"], ["屋内", "屋内"], ["アミューズメント", "アミューズメント"],["遺跡", "遺跡"],["城", "城"], ["飲食", "飲食"], ["お酒", "お酒"]], {include_blank: "地方選んで下さい"}, {class: 'formbox'}
            -# = f.collection_select :medium_area, @prefectures, :name, :name,  { prompt: "都道府県を選んで下さい" }, class: 'formbox'
          .Mainpost__inputcoment
            = f.text_area :content, class: 'Mainpost__comment', placeholder: 'コメントを入力して下さい'
          .Mainpost__level
            = f.select :level, [["★", "★"], ["★★", "★★"], ["★★★", "★★★"], ["★★★★", "★★★★"], ["★★★★★", "★★★★★"]], {include_blank: "ソロ活難易度を教えて下さい"}, {class: 'formbox'}

      .Checkgroup
        .Checkbox
          %ul.Checkbox__check
          -# = collection_check_boxes :post, Post.all, :check_box
          %li
            = f.check_box :check_1, {}, "初心者にオススメ", nil
            = label_tag :check_1, "初心者にオススメ"
          %li
            = f.check_box :check_2, {}, "中級者以上にオススメ", nil
            = label_tag :check_2, "中級者以上にオススメ"
          %li
            = f.check_box :check_3, {}, "上級者向け", nil
            = label_tag :check_3, "上級者向け"
          -# %li
          -#   = check_box :check_2, value = "中級者以上にオススメ"
          -#   = label_tag :check_2, "中級者以上にオススメ"
          -# %li
          -#   = check_box :check_3, value = "上級者向け"
          -#   = label_tag :check_3, "上級者向け"
        .Checkbox
          %ul.Checkbox__check
          %li
            = check_box_tag :check_4, value = "携帯電波有り"
            = label_tag :check_4, "携帯電波有り"
          %li
            = check_box_tag :check_5, value = "お一人様多数"
            = label_tag :check_5, "お一人様多数"
          %li
            = check_box_tag :check_6, value = "人通り[少]"
            = label_tag :check_6, "人通り[少]"

        .Checkbox
          %ul.Checkbox__check
          %li
            = check_box_tag :check_7, value = "カウンター席有り"
            = label_tag :check_7, "カウンター席有り"
          %li
            = check_box_tag :check_8, value = "近くに薬局"
            = label_tag :check_8, "近くに薬局"
          %li
            = check_box_tag :check_9, value = "アウェー感[小]"
            = label_tag :check_9, "アウェー感[小]"

    .Footer
      = f.submit '投稿する', class: 'Footer__menu'
    -# .Category
    -#   = @category.check

-# .Posts
-#   = form_with model: @post, html: {class: 'Mainpost'}, local: true do |f|
-#     .Mainpost__box
-#       = f.file_field :image, class: 'Mainpost__image'
-#       .Mainpost__right
-#         = f.text_field :areaname, class: 'Mainpost__inputname', placeholder: 'スポット名を入力'
-#         .Mainpost__inputarea
-#         = f.text_field :large_area, class: 'Mainpost__inputarea', placeholder: '広場所を入力'
-#         .Mainpost__inputcoment
-#         = f.text_field :content, class: 'Mainpost__comment', placeholder: 'コメントを入力'
-#         .Mainpost__inputspoint
-#           = f.text_field :check_1, class: 'Mainpost__inputspointe', placeholder: 'こだわりを入力'
-#     .Footer
-#       = f.submit '投稿する', class: 'Footer__menu'

app/views/posts/create.html.haml
.Contents
  .Success
    投稿が完了しました。
    .Successgroup
      .Successgroup__top
      = link_to "トップページに戻る", messages_path, class: 'Button'
      .Successgroup__post
      = link_to "投稿画面に戻る", posts_path, class: 'Button'

app/views/posts/index.html.haml
%html
  %head  
    = javascript_include_tag 'categories'

    .wrapper
      -# = render 'posts/postpage'
      = render 'posts/postpage'